"""challenge proposals + lifecycle

Revision ID: 20932c8fcabd
Revises: df8d401ae31a
Create Date: 2026-06-20 11:51:55.513578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20932c8fcabd'
down_revision: Union[str, Sequence[str], None] = 'df8d401ae31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('scoring', sa.String(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('spec', sa.String(), nullable=False),
    sa.Column('files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('author_key_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('reviewed_by_key_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_key_id'], ['keys.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_key_id'], ['keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_proposals_author_key_id'), ['author_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_proposals_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_challenge_proposals_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_proposals_status'), ['status'], unique=False)

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))
        # server_default backfills existing corpus rows; FK is named so SQLite batch can recreate it
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('deprecated', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('author_key_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_challenges_deprecated'), ['deprecated'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_challenges_author_key', 'keys', ['author_key_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_challenges_author_key', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_challenges_status'))
        batch_op.drop_index(batch_op.f('ix_challenges_deprecated'))
        batch_op.drop_column('author_key_id')
        batch_op.drop_column('deprecated')
        batch_op.drop_column('version')
        batch_op.drop_column('language')
        batch_op.drop_column('title')

    with op.batch_alter_table('challenge_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_challenge_proposals_slug'))
        batch_op.drop_index(batch_op.f('ix_challenge_proposals_content_hash'))
        batch_op.drop_index(batch_op.f('ix_challenge_proposals_author_key_id'))

    op.drop_table('challenge_proposals')
    # ### end Alembic commands ###
