"""initial schema

Revision ID: df8d401ae31a
Revises: 
Create Date: 2026-06-20 03:12:31.743323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df8d401ae31a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('verification', sa.String(), nullable=True),
    sa.Column('seed_difficulty', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_category'), ['category'], unique=False)

    op.create_table('key_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pubkey', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_challenges_nonce'), ['nonce'], unique=True)
        batch_op.create_index(batch_op.f('ix_key_challenges_pubkey'), ['pubkey'], unique=False)

    op.create_table('model_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('modality', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_families', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_families_name'), ['name'], unique=True)

    op.create_table('suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('official', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_suite')
    )
    with op.batch_alter_table('suites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suites_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('identity_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_identity')
    )
    with op.batch_alter_table('identity_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_links_user_id'), ['user_id'], unique=False)

    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pubkey', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keys_pubkey'), ['pubkey'], unique=True)

    op.create_table('model_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('artifact', sa.String(), nullable=False),
    sa.Column('hf_repo', sa.String(), nullable=False),
    sa.Column('hf_revision', sa.String(), nullable=True),
    sa.Column('file_sha256', sa.String(), nullable=True),
    sa.Column('params_total', sa.String(), nullable=True),
    sa.Column('params_active', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['model_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'hf_repo', 'artifact', 'file_sha256', name='uq_artifact')
    )
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_artifacts_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_artifacts_file_sha256'), ['file_sha256'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_hash', sa.String(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('suite_name', sa.String(), nullable=False),
    sa.Column('suite_version', sa.String(), nullable=False),
    sa.Column('engine', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sampling', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('serve_flags', sa.String(), nullable=True),
    sa.Column('context', sa.Integer(), nullable=True),
    sa.Column('env', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vram_gb', sa.Float(), nullable=True),
    sa.Column('harness_version', sa.String(), nullable=True),
    sa.Column('repro_sig', sa.String(), nullable=True),
    sa.Column('trust_tier', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['model_artifacts.id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_bundle_hash'), ['bundle_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_submissions_key_id'), ['key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_repro_sig'), ['repro_sig'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_suite_name'), ['suite_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_suite_version'), ['suite_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_trust_tier'), ['trust_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_vram_gb'), ['vram_gb'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('challenge_hash', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('verification', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('final', sa.Float(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('tok_per_s', sa.Float(), nullable=True),
    sa.Column('latency_s', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_results_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_submission_id'))
        batch_op.drop_index(batch_op.f('ix_results_challenge_id'))
        batch_op.drop_index(batch_op.f('ix_results_category'))

    op.drop_table('results')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_vram_gb'))
        batch_op.drop_index(batch_op.f('ix_submissions_trust_tier'))
        batch_op.drop_index(batch_op.f('ix_submissions_suite_version'))
        batch_op.drop_index(batch_op.f('ix_submissions_suite_name'))
        batch_op.drop_index(batch_op.f('ix_submissions_repro_sig'))
        batch_op.drop_index(batch_op.f('ix_submissions_key_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_bundle_hash'))
        batch_op.drop_index(batch_op.f('ix_submissions_artifact_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_artifacts_file_sha256'))
        batch_op.drop_index(batch_op.f('ix_model_artifacts_family_id'))

    op.drop_table('model_artifacts')
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keys_pubkey'))

    op.drop_table('keys')
    with op.batch_alter_table('identity_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_links_user_id'))

    op.drop_table('identity_links')
    op.drop_table('users')
    with op.batch_alter_table('suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suites_name'))

    op.drop_table('suites')
    with op.batch_alter_table('model_families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_families_name'))

    op.drop_table('model_families')
    with op.batch_alter_table('key_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_challenges_pubkey'))
        batch_op.drop_index(batch_op.f('ix_key_challenges_nonce'))

    op.drop_table('key_challenges')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_category'))

    op.drop_table('challenges')
    # ### end Alembic commands ###
