#!/usr/bin/env python3
"""Generate llama-swap config (serve/llama-swap.yaml) from serve/models.toml.

models.toml stays the single source of truth (serve.sh and bench.runner also read it).
llama-swap assigns upstream ports itself via the ${PORT} macro, so per-model `port`
values in models.toml are ignored here — llama-swap binds ONE LAN port and swaps the
upstream llama-server on demand based on the requested model name.

  python3 serve/gen_swap_config.py            # -> serve/llama-swap.yaml
"""
import tomllib, shlex
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LLAMA_SERVER = str(Path.home() / "llama.cpp/build/bin/llama-server")
REG = tomllib.load(open(ROOT / "serve/models.toml", "rb"))

def cmd_lines(m):
    gguf = str((ROOT / m["file"]).resolve())
    parts = [
        LLAMA_SERVER,
        f"--model {gguf}",
        "--port ${PORT} --host 127.0.0.1",
        f"-ngl 99 --jinja -c {m['ctx']}",
        m["flags"],
    ]
    # one flag-group per line for readability (llama-swap treats newlines as spaces)
    return "\n      ".join(parts)

out = [
    "# GENERATED by serve/gen_swap_config.py from serve/models.toml — do not edit by hand.",
    "# llama-swap binds one LAN port (see serve/llama-swap.service) and swaps the upstream",
    "# llama-server based on the requested model name. Request a model by its key below.",
    "",
    "# Big models + large KV pre-alloc can take ~1-2 min to load; give the health check room.",
    "healthCheckTimeout: 300",
    "",
    "models:",
]
for name, m in REG.items():
    out.append(f"  {name}:")
    out.append(f"    cmd: |")
    out.append(f"      {cmd_lines(m)}")
    # keep a model resident until a different one is requested (swap-on-request handles VRAM);
    # no idle auto-unload so the coder stays warm.
    out.append(f"    ttl: 0")
    out.append("")

(ROOT / "serve/llama-swap.yaml").write_text("\n".join(out) + "\n")
print("wrote serve/llama-swap.yaml with models:", ", ".join(REG.keys()))
