# ⚠ COPYRIGHT NOTICE: AIME problems are copyrighted by the MAA (Mathematical Association of America).
#   The generated corpus is gitignored and must NOT be committed or published to peakstone.ai.
#   Use only as PRIVATE challenges (you accept the upstream terms). Not part of the public suite.
"""Import AIME competition problems as peakstone answer-match challenges.

AIME (American Invitational Mathematics Examination) is naturally contamination-resistant: it's an
annual, dated competition, so each year's problems postdate models released before it. AIME 2026
(Feb 2026) is held-out for most of the current roster — a clean timeline point that needs no scraper.

Grading is deterministic answer-match (integer 0-999), not code execution: the runner's
`scoring="answer-match"` path extracts the model's final answer and compares to the gold in meta
`expect`. So these are a separate axis from code_score.

Sources are date-stamped HF datasets (problem + answer); imported via the datasets-server rows API.
By default imports AIME 2025 and 2026 into one `aime` suite.

Usage:
  python -m peakstone.engine.importers.aime
  python -m peakstone.engine.importers.aime --source math-ai/aime25 --split test \\
      --published-at 2025-02-06 --id-prefix aime25
"""
from __future__ import annotations

import argparse
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from .. import paths
from ._common import hf_rows, meta_toml
from .humaneval import _slug


@dataclass
class Source:
    dataset: str
    split: str
    published_at: str          # earliest public date of that year's exam (contamination boundary)
    id_prefix: str
    config: str = "default"
    problem_field: str = "problem"
    answer_field: str = "answer"


# AIME I is held in early February; use that date as the conservative publish boundary.
DEFAULT_SOURCES = [
    Source("math-ai/aime25", "test", "2025-02-06", "aime25"),
    Source("MathArena/aime_2026", "train", "2026-02-05", "aime26"),
]


def _fetch(src: Source) -> list[dict]:
    return hf_rows(src.dataset, src.config, src.split)


def _difficulty(i: int) -> int:
    # AIME problems escalate within a paper (1..15); later problems are harder.
    pos = i % 15
    return 3 if pos < 5 else 4 if pos < 10 else 5


def _meta(cid, title, difficulty, answer, published_at, timeout) -> str:
    return meta_toml(cid, title, "text", difficulty, "math", "math", "answer-match",
                     "", timeout, published_at, expect=answer)   # expect: the gold integer answer


def _spec(problem: str, src: Source, idx: int) -> str:
    return (f"# AIME {src.id_prefix[-2:]} Problem {idx}\n\n"
            f"{problem.rstrip()}\n\n"
            "Give your final answer as an integer between 0 and 999.\n"
            f"\n<!-- imported from {src.dataset} ({src.split}) -->\n")


def import_suite(sources, out_root, suite, timeout, limit):
    suite_dir = out_root / suite
    if suite_dir.exists():
        shutil.rmtree(suite_dir)
    suite_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    for src in sources:
        rows = _fetch(src)
        for i, r in enumerate(rows):
            if limit and written >= limit:
                break
            problem = str(r.get(src.problem_field, "")).strip()
            answer = str(r.get(src.answer_field, "")).strip()
            if not problem or not answer:
                continue
            cid = f"{src.id_prefix}-{i:02d}"
            slug = _slug(problem[:50]) or "problem"
            cdir = suite_dir / f"{cid}-{slug}"
            cdir.mkdir(parents=True, exist_ok=True)
            (cdir / "meta.toml").write_text(
                _meta(cid, f"AIME {src.id_prefix[-2:]} #{i + 1}", _difficulty(i), answer,
                      src.published_at, timeout))
            (cdir / "spec.md").write_text(_spec(problem, src, i + 1))
            written += 1

    (suite_dir / "SOURCE.md").write_text(
        f"# AIME\n\n{written} answer-match challenges auto-generated by "
        f"`peakstone.engine.importers.aime`.\n\n"
        f"- **Sources:** {', '.join(s.dataset for s in sources)}\n"
        f"- **Grading:** deterministic answer-match (integer); a separate axis from code_score.\n"
        f"- **Contamination:** each year is dated by its exam ("
        f"{', '.join(s.published_at for s in sources)}); AIME is annual so newer years are held-out "
        f"for models released earlier.\n"
        f"- **License:** problems are from the AIME (MAA); see each upstream dataset for terms.\n")
    return written


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", default=None, help="single HF dataset id (else the built-in 2025+2026 set)")
    ap.add_argument("--config", default="default")
    ap.add_argument("--split", default="test")
    ap.add_argument("--problem-field", default="problem")
    ap.add_argument("--answer-field", default="answer")
    ap.add_argument("--published-at", default=None, help="exam date YYYY-MM-DD (required with --source)")
    ap.add_argument("--id-prefix", default="aime")
    ap.add_argument("--out", default=None)
    ap.add_argument("--suite", default="aime")
    ap.add_argument("--timeout", type=int, default=30)
    ap.add_argument("--limit", type=int, default=None)
    args = ap.parse_args(argv)

    if args.source:
        if not args.published_at:
            ap.error("--published-at is required with --source")
        sources = [Source(args.source, args.split, args.published_at, args.id_prefix,
                          args.config, args.problem_field, args.answer_field)]
    else:
        sources = DEFAULT_SOURCES

    out_root = Path(args.out) if args.out else paths.challenges_dir()
    n = import_suite(sources, out_root, args.suite, args.timeout, args.limit)
    print(f"imported {n} AIME challenges -> {out_root / args.suite}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
